language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgnutls-dev
      
install: false

branches:
  only:
- master

# Compiler selection
compiler: gcc

script:
   make –f Makefile-unix-shared