language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgnutls-dev
    
branches:
  only:
- master

# Compiler selection
compiler:
- gcc

script:
   make –f Makefile-unix-shared