language: cpp

dist: trusty
sudo: required

os:
- linux

# Compiler selection
compiler:
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgnutls-dev
      
install: false

branches:
  only:
    - master

script:
  - make --file=Makefile-unix-shared