language: cpp

dist: trusty
sudo: required

os:
  - linux

branches:
  only:
    - master
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgnutls-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"
  - wget https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.17.tar.xz
  - tar -xvf gnutls-3.5.17.tar.xz
  - pushd gnutls-3.5.17 && ./configure && make && sudo make install && popd
    
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .