language: cpp

dist: trusty
sudo: required

os:
  - linux

branches:
  only:
    - master
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"
  
script:  
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DNO_EXCEPTIONS=ON -DNO_RTTI=ON
  - cmake --build .