language: cpp

dist: trusty
sudo: required

os:
  - linux

branches:
  only:
    - master
    
matrix:
  include:
- os: linux
  compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: ['g++-7','libgnutls-dev']
      install: export CXX="g++-7"
      env: CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-std=c++17"

    
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .