# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = cmake.exe

# The command to remove a file.
RM = cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/cpp/io

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/cpp/io

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/cpp/io/CMakeFiles /d/cpp/io/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/cpp/io/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libio

# Build rule for target.
libio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libio
.PHONY : libio

# fast build rule for target.
libio/fast:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/build
.PHONY : libio/fast

src/buffer.o: src/buffer.cpp.o

.PHONY : src/buffer.o

# target to build an object file
src/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/buffer.cpp.o
.PHONY : src/buffer.cpp.o

src/buffer.i: src/buffer.cpp.i

.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s

.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/channels.o: src/channels.cpp.o

.PHONY : src/channels.o

# target to build an object file
src/channels.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/channels.cpp.o
.PHONY : src/channels.cpp.o

src/channels.i: src/channels.cpp.i

.PHONY : src/channels.i

# target to preprocess a source file
src/channels.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/channels.cpp.i
.PHONY : src/channels.cpp.i

src/channels.s: src/channels.cpp.s

.PHONY : src/channels.s

# target to generate assembly for a file
src/channels.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/channels.cpp.s
.PHONY : src/channels.cpp.s

src/charsetcvt.o: src/charsetcvt.cpp.o

.PHONY : src/charsetcvt.o

# target to build an object file
src/charsetcvt.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsetcvt.cpp.o
.PHONY : src/charsetcvt.cpp.o

src/charsetcvt.i: src/charsetcvt.cpp.i

.PHONY : src/charsetcvt.i

# target to preprocess a source file
src/charsetcvt.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsetcvt.cpp.i
.PHONY : src/charsetcvt.cpp.i

src/charsetcvt.s: src/charsetcvt.cpp.s

.PHONY : src/charsetcvt.s

# target to generate assembly for a file
src/charsetcvt.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsetcvt.cpp.s
.PHONY : src/charsetcvt.cpp.s

src/charsets.o: src/charsets.cpp.o

.PHONY : src/charsets.o

# target to build an object file
src/charsets.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsets.cpp.o
.PHONY : src/charsets.cpp.o

src/charsets.i: src/charsets.cpp.i

.PHONY : src/charsets.i

# target to preprocess a source file
src/charsets.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsets.cpp.i
.PHONY : src/charsets.cpp.i

src/charsets.s: src/charsets.cpp.s

.PHONY : src/charsets.s

# target to generate assembly for a file
src/charsets.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/charsets.cpp.s
.PHONY : src/charsets.cpp.s

src/codedetect.o: src/codedetect.cpp.o

.PHONY : src/codedetect.o

# target to build an object file
src/codedetect.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/codedetect.cpp.o
.PHONY : src/codedetect.cpp.o

src/codedetect.i: src/codedetect.cpp.i

.PHONY : src/codedetect.i

# target to preprocess a source file
src/codedetect.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/codedetect.cpp.i
.PHONY : src/codedetect.cpp.i

src/codedetect.s: src/codedetect.cpp.s

.PHONY : src/codedetect.s

# target to generate assembly for a file
src/codedetect.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/codedetect.cpp.s
.PHONY : src/codedetect.cpp.s

src/posix/files.o: src/posix/files.cpp.o

.PHONY : src/posix/files.o

# target to build an object file
src/posix/files.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/posix/files.cpp.o
.PHONY : src/posix/files.cpp.o

src/posix/files.i: src/posix/files.cpp.i

.PHONY : src/posix/files.i

# target to preprocess a source file
src/posix/files.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/posix/files.cpp.i
.PHONY : src/posix/files.cpp.i

src/posix/files.s: src/posix/files.cpp.s

.PHONY : src/posix/files.s

# target to generate assembly for a file
src/posix/files.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/posix/files.cpp.s
.PHONY : src/posix/files.cpp.s

src/shared_library.o: src/shared_library.cpp.o

.PHONY : src/shared_library.o

# target to build an object file
src/shared_library.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/shared_library.cpp.o
.PHONY : src/shared_library.cpp.o

src/shared_library.i: src/shared_library.cpp.i

.PHONY : src/shared_library.i

# target to preprocess a source file
src/shared_library.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/shared_library.cpp.i
.PHONY : src/shared_library.cpp.i

src/shared_library.s: src/shared_library.cpp.s

.PHONY : src/shared_library.s

# target to generate assembly for a file
src/shared_library.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/shared_library.cpp.s
.PHONY : src/shared_library.cpp.s

src/stdafx.o: src/stdafx.cpp.o

.PHONY : src/stdafx.o

# target to build an object file
src/stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stdafx.cpp.o
.PHONY : src/stdafx.cpp.o

src/stdafx.i: src/stdafx.cpp.i

.PHONY : src/stdafx.i

# target to preprocess a source file
src/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stdafx.cpp.i
.PHONY : src/stdafx.cpp.i

src/stdafx.s: src/stdafx.cpp.s

.PHONY : src/stdafx.s

# target to generate assembly for a file
src/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stdafx.cpp.s
.PHONY : src/stdafx.cpp.s

src/stringpool.o: src/stringpool.cpp.o

.PHONY : src/stringpool.o

# target to build an object file
src/stringpool.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stringpool.cpp.o
.PHONY : src/stringpool.cpp.o

src/stringpool.i: src/stringpool.cpp.i

.PHONY : src/stringpool.i

# target to preprocess a source file
src/stringpool.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stringpool.cpp.i
.PHONY : src/stringpool.cpp.i

src/stringpool.s: src/stringpool.cpp.s

.PHONY : src/stringpool.s

# target to generate assembly for a file
src/stringpool.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/stringpool.cpp.s
.PHONY : src/stringpool.cpp.s

src/text.o: src/text.cpp.o

.PHONY : src/text.o

# target to build an object file
src/text.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/text.cpp.o
.PHONY : src/text.cpp.o

src/text.i: src/text.cpp.i

.PHONY : src/text.i

# target to preprocess a source file
src/text.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/text.cpp.i
.PHONY : src/text.cpp.i

src/text.s: src/text.cpp.s

.PHONY : src/text.s

# target to generate assembly for a file
src/text.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/text.cpp.s
.PHONY : src/text.cpp.s

src/win/console.o: src/win/console.cpp.o

.PHONY : src/win/console.o

# target to build an object file
src/win/console.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/console.cpp.o
.PHONY : src/win/console.cpp.o

src/win/console.i: src/win/console.cpp.i

.PHONY : src/win/console.i

# target to preprocess a source file
src/win/console.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/console.cpp.i
.PHONY : src/win/console.cpp.i

src/win/console.s: src/win/console.cpp.s

.PHONY : src/win/console.s

# target to generate assembly for a file
src/win/console.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/console.cpp.s
.PHONY : src/win/console.cpp.s

src/win/files.o: src/win/files.cpp.o

.PHONY : src/win/files.o

# target to build an object file
src/win/files.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/files.cpp.o
.PHONY : src/win/files.cpp.o

src/win/files.i: src/win/files.cpp.i

.PHONY : src/win/files.i

# target to preprocess a source file
src/win/files.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/files.cpp.i
.PHONY : src/win/files.cpp.i

src/win/files.s: src/win/files.cpp.s

.PHONY : src/win/files.s

# target to generate assembly for a file
src/win/files.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/win/files.cpp.s
.PHONY : src/win/files.cpp.s

src/xml_error.o: src/xml_error.cpp.o

.PHONY : src/xml_error.o

# target to build an object file
src/xml_error.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_error.cpp.o
.PHONY : src/xml_error.cpp.o

src/xml_error.i: src/xml_error.cpp.i

.PHONY : src/xml_error.i

# target to preprocess a source file
src/xml_error.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_error.cpp.i
.PHONY : src/xml_error.cpp.i

src/xml_error.s: src/xml_error.cpp.s

.PHONY : src/xml_error.s

# target to generate assembly for a file
src/xml_error.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_error.cpp.s
.PHONY : src/xml_error.cpp.s

src/xml_event.o: src/xml_event.cpp.o

.PHONY : src/xml_event.o

# target to build an object file
src/xml_event.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_event.cpp.o
.PHONY : src/xml_event.cpp.o

src/xml_event.i: src/xml_event.cpp.i

.PHONY : src/xml_event.i

# target to preprocess a source file
src/xml_event.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_event.cpp.i
.PHONY : src/xml_event.cpp.i

src/xml_event.s: src/xml_event.cpp.s

.PHONY : src/xml_event.s

# target to generate assembly for a file
src/xml_event.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_event.cpp.s
.PHONY : src/xml_event.cpp.s

src/xml_parse.o: src/xml_parse.cpp.o

.PHONY : src/xml_parse.o

# target to build an object file
src/xml_parse.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_parse.cpp.o
.PHONY : src/xml_parse.cpp.o

src/xml_parse.i: src/xml_parse.cpp.i

.PHONY : src/xml_parse.i

# target to preprocess a source file
src/xml_parse.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_parse.cpp.i
.PHONY : src/xml_parse.cpp.i

src/xml_parse.s: src/xml_parse.cpp.s

.PHONY : src/xml_parse.s

# target to generate assembly for a file
src/xml_parse.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_parse.cpp.s
.PHONY : src/xml_parse.cpp.s

src/xml_source.o: src/xml_source.cpp.o

.PHONY : src/xml_source.o

# target to build an object file
src/xml_source.cpp.o:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_source.cpp.o
.PHONY : src/xml_source.cpp.o

src/xml_source.i: src/xml_source.cpp.i

.PHONY : src/xml_source.i

# target to preprocess a source file
src/xml_source.cpp.i:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_source.cpp.i
.PHONY : src/xml_source.cpp.i

src/xml_source.s: src/xml_source.cpp.s

.PHONY : src/xml_source.s

# target to generate assembly for a file
src/xml_source.cpp.s:
	$(MAKE) -f CMakeFiles/libio.dir/build.make CMakeFiles/libio.dir/src/xml_source.cpp.s
.PHONY : src/xml_source.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libio"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/channels.o"
	@echo "... src/channels.i"
	@echo "... src/channels.s"
	@echo "... src/charsetcvt.o"
	@echo "... src/charsetcvt.i"
	@echo "... src/charsetcvt.s"
	@echo "... src/charsets.o"
	@echo "... src/charsets.i"
	@echo "... src/charsets.s"
	@echo "... src/codedetect.o"
	@echo "... src/codedetect.i"
	@echo "... src/codedetect.s"
	@echo "... src/posix/files.o"
	@echo "... src/posix/files.i"
	@echo "... src/posix/files.s"
	@echo "... src/shared_library.o"
	@echo "... src/shared_library.i"
	@echo "... src/shared_library.s"
	@echo "... src/stdafx.o"
	@echo "... src/stdafx.i"
	@echo "... src/stdafx.s"
	@echo "... src/stringpool.o"
	@echo "... src/stringpool.i"
	@echo "... src/stringpool.s"
	@echo "... src/text.o"
	@echo "... src/text.i"
	@echo "... src/text.s"
	@echo "... src/win/console.o"
	@echo "... src/win/console.i"
	@echo "... src/win/console.s"
	@echo "... src/win/files.o"
	@echo "... src/win/files.i"
	@echo "... src/win/files.s"
	@echo "... src/xml_error.o"
	@echo "... src/xml_error.i"
	@echo "... src/xml_error.s"
	@echo "... src/xml_event.o"
	@echo "... src/xml_event.i"
	@echo "... src/xml_event.s"
	@echo "... src/xml_parse.o"
	@echo "... src/xml_parse.i"
	@echo "... src/xml_parse.s"
	@echo "... src/xml_source.o"
	@echo "... src/xml_source.i"
	@echo "... src/xml_source.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

