name: build

on:
  push:
    branches:
      - 'master'
      - 'refactor'
    pull_request:

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu]
      compiler: [g++, clang++]
    name: ${{matrix.os}} (${{matrix.compiler}}, ${{matrix.defines}})
    steps:
      - uses: actions/checkout@v1
      - name: cmake configure
        run: cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRARY_TYPE=Static -D${{matrix.defines}}=ON -A ${{matrix.arch}}
      - name: cmake build
        run: cmake --build .

windows:
  runs-on: windows-latest
  strategy:
    matrix:
      arch: [Win32, x64]
      defines: [_WIN32_WINNT=0x0A00]
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRARY_TYPE=Static -D${{matrix.defines}}=ON -A ${{matrix.arch}}
    - name: cmake build
      run: MSBuild io.sln /p:Configuration=Release
