name: build

on:
  push:
    branches:
      - 'master'
      - 'refactor'
    pull_request:

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu]
        compiler: [g++]
    name: ${{matrix.os}} (${{matrix.compiler}}
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: sudo apt-get install -y gnutls-dev
      - name: cmake configure
        run: cmake IO -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRARY_TYPE=Shared
      - name: cmake build
        run: cmake IO --build
# windows:    
#   strategy:
#      matrix:
#        arch: [Win32, x64]
#    name: windows ${{matrix.arch}}   
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: cmake configure
#        run: cmake . -G "Visual Studio 17 2022" -A ${{matrix.arch}} -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRARY_TYPE=Static
#      - name: cmake build
#        run: MSBuild io.sln /p:Configuration=Release
